#!/bin/sh /etc/rc.common
# description: Cosmos Cloud server (self-hosted secure gateway)
# processname: cosmos

START=99
STOP=01
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /opt/cosmos/cosmos
	procd_set_param env COSMOS_CONFIG_FOLDER=/etc/cosmos/
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 150 10 10
	procd_close_instance
}

stop_service() {
	procd_kill cosmos 2>/dev/null
	kill -9 "$(pidof cosmos)" 2>/dev/null
}